name: Update Website



on:

  schedule:

    - cron: '* * * *'  # Runs every minute



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: |

        # Your custom script to update website content

        python update_content.py

        git config user.name 'GitHub Actions Bot'

        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

        git add .

        git commit -m "Automatic website update"

        git push origin HEAD:gh-pages
