name: Update Website



on:

  push:  # Runs every 10 minutes
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: echo ls >> log.txt
