name: Update Website



on:

  schedule:

    - cron: '0,10,20,30,40,50 * * *'  # Runs every 10 minutes



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: python update_content.py

      - run : git add .

      - run : git commit -m "Automatic website update"

      - run : git push origin HEAD:gh-pages
