name: Update Website

on: 
  push:

  schedule:

    - cron: '0,10,20,30,40,50 * * * *'  # Runs every 10 minutes
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: echo "$PWD"
    - run: ls -a
    - run: git config --global user.email "jcaulkins@wisc.edu"
    - run: git config --global user.name "jcaulkins"
    - run: chmod +x update_daily.sh
    - run: pip3 install beautifulsoup4
    - run: ./update_daily.sh
